language: scala
jdk:
  - openjdk8

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    - env: TEST="scalafmt"
      script: sbt scalafmtCheckAll
    - env: TEST="sbt test"
      script: sbt test
    - stage: release
      script: sbt ci-release

before_install:
  - git fetch --tags
